### PR TITLE
lower the min, default, and default max alloc lifetime to 20s

### PR DESCRIPTION
**Pull request by neonphog**

### CODE REVIEW

**Comment by steveej** [comment]
can these not be changed at via the config or is there a bug in the application of the config?

the title mentions "min" yet i'm not seeing any minimum changed. is it actually there? depending on the above it seems like it would be enough to lower the min and then set that via the config.

**Comment by neonphog** [comment]
@steveej - Note the line in between my two changed lines!

Yes, if we were wanting to submit this back to upstream we'd want to make it configurable. I was thinking this was more along the lines of let's quickly fix our current problem : )

**Comment by steveej** [comment]
what's the cost of a refresh? every 10s does seem often.

to quote yourself

> and sets up a timer to refresh at half the returned lifetime: https://github.com/pion/turn/blob/master/internal/client/udp_conn.go#L68-L72

**Comment by neonphog** [comment]
@steveej 

> what's the cost of a refresh? every 10s does seem often.

One network round trip on the happy path, more if it needs to retransmit.

**Comment by neonphog** [comment]
@steveej

> what's the cost of a refresh? every 10s does seem often.

For the purposes of clearing up our sessions / relay ports on our servers, I'd think of it more in the reverse. What's the shortest time we can have and still have this work?

That would be limited by slow connections transmitting too much data. The largest chunk size for a data channel is 16KiB... so if the client takes more than 20s to transmit a chunk (~7 kbps), the connection could be closed because it didn't refresh in time.

I'm actually okay with that. A connection that slow isn't going to be super usable from the end-user perspective and maybe shouldn't be taking up our resources anyways, right?

**Review by steveej — APPROVED** [review]
i'm onboard giving this a try and measure the outcome.

**Pull request merged**
